# Generated by Django 3.0.8 on 2020-12-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
                ('orderitems', models.CharField(max_length=10)),
            ],
        ),
    ]
